# Generated by Django 2.1 on 2018-08-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0002_auto_20180827_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='date_sow_end',
            field=models.IntegerField(verbose_name='date sowing season ends'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='date_sow_ini',
            field=models.IntegerField(verbose_name='date sowing season starts'),
        ),
    ]
