# Generated by Django 2.1 on 2018-08-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False
    
    dependencies = [
        ('hortadb', '0003_auto_20180828_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plant_Generic',
            new_name='Plant',
        ),
        migrations.AlterField(
            model_name='seed',
            name='date_packing',
            field=models.DateField(verbose_name='date packing of seeds'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='date_validity',
            field=models.DateField(verbose_name='expiry date of seeds'),
        ),
    ]
