# Generated by Django 2.1 on 2018-08-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0004_auto_20180828_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seed_Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_packing', models.DateField(verbose_name='date packing of seeds')),
                ('date_validity', models.DateField(verbose_name='expiry date of seeds')),
                ('weight', models.IntegerField(verbose_name='weight of seed bag [g]')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='seed',
            name='date_packing',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='date_validity',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='species',
        ),
        migrations.AddField(
            model_name='seed',
            name='origin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='seed',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hortadb.Cultivar'),
        ),
        migrations.AddField(
            model_name='seed_packet',
            name='plant_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hortadb.Seed'),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hortadb.Species'),
        ),
    ]
