# Generated by Django 2.1 on 2018-08-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0005_auto_20180831_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
