# Generated by Django 2.1 on 2018-09-02 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0007_cultivar_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
    ]
