# Generated by Django 2.1 on 2018-09-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0008_species_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'species'},
        ),
    ]
