# Generated by Django 2.1 on 2018-09-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0009_auto_20180902_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivar',
            name='life_cycle',
            field=models.CharField(choices=[('AN', 'annual'), ('BI', 'biennial'), ('PR', 'perennial'), ('UN', 'unknown')], default='UN', max_length=20),
        ),
    ]
