# Generated by Django 2.1 on 2018-09-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0010_cultivar_life_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivar',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='origin',
        ),
        migrations.AlterField(
            model_name='seed',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='brand/origin'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='date_sow_end',
            field=models.IntegerField(verbose_name='month sowing season ends'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='date_sow_ini',
            field=models.IntegerField(verbose_name='month sowing season starts'),
        ),
    ]
