# Generated by Django 2.1 on 2018-09-03 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0013_auto_20180903_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='date_harv_end',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month harvesting ends'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seed',
            name='date_harv_ini',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month harvesting starts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seed',
            name='date_tran_end',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month transplanting ends'),
        ),
        migrations.AddField(
            model_name='seed',
            name='date_tran_ini',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month transplanting starts'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='date_sow_end',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month sowing ends'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='date_sow_ini',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month sowing starts'),
        ),
    ]
