# Generated by Django 2.1 on 2018-09-03 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0015_remove_species_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='date_sow_end',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='date_sow_ini',
        ),
        migrations.AddField(
            model_name='seed',
            name='date_sowi_end',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month sowing inside ends'),
        ),
        migrations.AddField(
            model_name='seed',
            name='date_sowi_ini',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month sowing inside starts'),
        ),
        migrations.AddField(
            model_name='seed',
            name='date_sowo_end',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month sowing outside ends'),
        ),
        migrations.AddField(
            model_name='seed',
            name='date_sowp_ini',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month sowing outside starts'),
        ),
    ]
