# Generated by Django 2.1 on 2018-09-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0016_auto_20180903_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seed',
            old_name='date_sowp_ini',
            new_name='date_sowo_ini',
        ),
    ]
