# Generated by Django 2.1 on 2018-09-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0018_auto_20180903_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed_packet',
            name='date_packing',
            field=models.DateField(verbose_name='packing date of seed bag'),
        ),
        migrations.AlterField(
            model_name='seed_packet',
            name='date_validity',
            field=models.DateField(verbose_name='expiry date of seed bag'),
        ),
    ]
