# Generated by Django 2.1 on 2018-09-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0019_auto_20180904_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seed',
            old_name='variety',
            new_name='plant_seed',
        ),
    ]
