# Generated by Django 2.1 on 2018-09-06 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0021_auto_20180904_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='date_harv_end',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month harvesting ends'),
        ),
        migrations.AlterField(
            model_name='seed',
            name='date_harv_ini',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='month harvesting starts'),
        ),
    ]
