# Generated by Django 2.1 on 2018-09-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0022_auto_20180906_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed_packet',
            name='date_packing',
            field=models.DateField(blank=True, null=True, verbose_name='packing date of seed bag'),
        ),
        migrations.AlterField(
            model_name='seed_packet',
            name='date_validity',
            field=models.DateField(blank=True, null=True, verbose_name='expiry date of seed bag'),
        ),
    ]
