# Generated by Django 2.1 on 2018-09-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0024_auto_20180909_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='germination_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='average weight of fruit [cm]'),
        ),
    ]
