# Generated by Django 2.1.1 on 2018-09-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0025_seed_germination_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='subspecies',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
