# Generated by Django 2.1.1 on 2018-09-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0027_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='channel',
            new_name='channel_name',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='link',
            new_name='playlist_link',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='name',
            new_name='playlist_name',
        ),
        migrations.AddField(
            model_name='playlist',
            name='short_description',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
