# Generated by Django 2.1.1 on 2018-09-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hortadb', '0028_auto_20180920_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='short_description',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
